//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.MaPhieuDKs = new HashSet<MaPhieuDK>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string MotaPhong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual GiaPhong GiaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaPhieuDK> MaPhieuDKs { get; set; }
    }
}
